# Generated by Django 3.1.7 on 2021-03-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(choices=[(1, 'LiveMe'), (2, 'Fluxr'), (3, 'DSP')], default=1, verbose_name='应用id）')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='是否被删除')),
                ('title', models.CharField(max_length=255, verbose_name='文章标题')),
                ('type', models.IntegerField(db_index=True, verbose_name='文章类型')),
                ('content', models.IntegerField(verbose_name='文章内容')),
                ('operator', models.CharField(max_length=255, verbose_name='操作人')),
                ('extra', models.TextField(default={}, verbose_name='额外信息')),
            ],
            options={
                'verbose_name': '文章集合',
                'db_table': 'blog_article',
            },
        ),
    ]
